package com.example.asus.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.asus.greendao.entity.DoubleRecord;
import com.example.asus.greendao.entity.SingleRecord;

import com.example.asus.greendao.DoubleRecordDao;
import com.example.asus.greendao.SingleRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig doubleRecordDaoConfig;
    private final DaoConfig singleRecordDaoConfig;

    private final DoubleRecordDao doubleRecordDao;
    private final SingleRecordDao singleRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        doubleRecordDaoConfig = daoConfigMap.get(DoubleRecordDao.class).clone();
        doubleRecordDaoConfig.initIdentityScope(type);

        singleRecordDaoConfig = daoConfigMap.get(SingleRecordDao.class).clone();
        singleRecordDaoConfig.initIdentityScope(type);

        doubleRecordDao = new DoubleRecordDao(doubleRecordDaoConfig, this);
        singleRecordDao = new SingleRecordDao(singleRecordDaoConfig, this);

        registerDao(DoubleRecord.class, doubleRecordDao);
        registerDao(SingleRecord.class, singleRecordDao);
    }
    
    public void clear() {
        doubleRecordDaoConfig.clearIdentityScope();
        singleRecordDaoConfig.clearIdentityScope();
    }

    public DoubleRecordDao getDoubleRecordDao() {
        return doubleRecordDao;
    }

    public SingleRecordDao getSingleRecordDao() {
        return singleRecordDao;
    }

}
